### ISSUE TITLE
"Backed up" instead of "Backuped"  :)

### ISSUE THREAD

**Issue by malebuffy** [chervonij/DFL-Colab#11]
I know its nothing but my eyes hurt everytime the workspace is uploaded to the drive. There is a spelling mistake I cannot unsee! LoL

Great work btw!!!

https://ell.stackexchange.com/questions/113044/is-adjective-backuped-correct

**Comment by chervonij** [comment]
@malebuffy 
Hi!
Thank you for noticing this =)
I was not sure how to translate correctly, because Google Translate does not see the difference between "backed up" and "backuped". I will definitely fix it.

I'm glad that DFL-Colab is useful for you )

**Comment by chervonij** [comment]
@malebuffy 
Fixed in the last update )
