### ISSUE TITLE
TypeError: object of type 'PosixPath' has no len()

### ISSUE THREAD

**Issue by l0ophole** [chervonij/DFL-Colab#16]
OS: Debian Linux
GPU: Nvidia T4
CUDA: 10.0.130-1
Python: 3.6
Command line: python3.6 DeepFaceLab/main.py merge --input-dir workspace/data_dst --output-dir workspace/data_dst/merged --output-mask-dir workspace/data_dst/merged_mask --aligned-dir workspace/data_dst/aligned --model-dir workspace/model --model "SAEHD"

I've been training a model for the past 48 hours and I have already merged the model and exported it to a video twice with no problems. I just tried to merge the model again and now it gets to frame 95 and crashes. See the error log below this paragraph. Is my model useless now? I've been training it on a Google Compute VM so if the model is useless then I've wasted $10 on the Google Compute VM so far.

Merging:   3% 95/3623 [00:05<03:27, 17.00it/s]Exception while process data [/content/workspace/data_dst/00096.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [/content/workspace/data_dst/00096.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Exception while process data [/content/workspace/data_dst/00097.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [/content/workspace/data_dst/00097.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by chervonij** [comment]
@l0ophole 
As far as I know, this bug has been fixed in DFL. 
And secondly, I do not support Google Cloud. 
Only Google Colab (as should be clear from the name of the repository)

**Comment by l0ophole** [comment]
I moved the training to Google Cloud because my model got corrupted after running 300K iterations in Colab. I don't know if you recently added version 2 of the project but I believe I was training in version 1 and after I got disconnected after 12 hours I could not use the model anymore because the images were corrupted and looked nothing like the source or destination data anymore. 
I was actually able to use the merge function after I posted this issue. I had trained the model about 8 more hours since I received the above error while trying to use the merge function. I don't know if it's working now because of the additional training or if there was a bug fix in the repo. 
Can you tell me how you are making the merge function with in Colab without using an Xserver? I tried to do the merge on my Google Compute VM but it's saying it can't connect to display :1. I tried it again after installing vncserver and then again after installing Xvfb+x11vnc but the merge function would hang indefinitely on the very first image (i.e. 000001.jpg). Is there a way to run the merge without needing to have an Xserver running? I read the code in the Colab notebook but it seemed to be executing the same command with the same parameters as I was attempting to do in Google Compute.

Thank you

**Comment by chervonij** [comment]
@l0ophole 
Again. I do not work with Google Cloud.
In theory, on any Linux VM (Cloud or Local), the launch is performed using the same scripts. Problem can only be in the DFL version that you use on Google Cloud. Colab makes a clone of latest version from master.

About Xserver. I do not work with Google Cloud and therefore do not use this. Colab is provided with a ready-made IPython interface in browser and no Xserver is needed there.

**Comment by l0ophole** [comment]
@chervonij I understand that you don't work with Google cloud. I'm asking about xserver because I cloned deepfacelab from the official repo and when I run 'python3.6 merge ...' it gives me the 'could not connect to display :1' error, so I assumed you must have been doing something in the colab version to avoid needing an xserver to be running during the merge. It's odd that I get an error about not being able to open a display when I run the same command line that you have for the merge function in the Colab notebook.

Is there a way to know how much time you have left before Colab will disconnect you? I was just running a merge and exporting to a video a few minutes ago and Colab disconnected me before the video export finished. The merge and the export had been running for almost two hours and when I reconnected everything had been deleted.

**Comment by chervonij** [comment]
@l0ophole 
Colab doesn't need Xserver. 
Therefore, I can not advise you about this.

Colab may disconnect before the end of session. This happens random(or by some non-obvious Google algorithms). Just start over and don’t forget to backup whenever possible.
If you need a code to check amount of time until the end of session, then look in "Train" block. 
There is a simple timer for calculating this.

Also check out the MrDeepFakes forum guide and discussion thread. 
There is more information about Disconnects and how people solve them.

**Comment by l0ophole** [comment]
Thanks :-)
