### ISSUE TITLE
pretrain faceset download error

### ISSUE THREAD

**Issue by camjac251** [chervonij/DFL-Colab#18]
I am trying to run the first step on the DFL colab latest notebook but get this error on the last part of it. DeepFaceLab uses `faceset.pak` which could simplify things, not needing to unzip etc.

I'll try to figure it out locally and create a pull request
```bash
[/content/pretrain_CelebA.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /content/pretrain_CelebA.zip or
        /content/pretrain_CelebA.zip.zip, and cannot find /content/pretrain_CelebA.zip.ZIP, period.
```

**Comment by camjac251** [comment]
I just tried it again and it worked. Not sure if it was a bug or what

**Comment by chervonij** [comment]
@camjac251 
yes, it's problem with gdrive.
I work to fix this

**Comment by chervonij** [comment]
@camjac251 
fixed. 
now downloads from github.
there should be no problems.

**Comment by camjac251** [comment]
Oh cool thanks. Would it be possible for some error handling with the download if it fails?

I also think I got an OOM error but it didn't look like a usual one

```
tcmalloc: large alloc 2017501184 bytes == 0x131d64000 @  0x7f00cbde02a4 0x592727 0x4dddf7 0x4e3200 0x4e284a 0x4e14d8 0x4e2c5b 0x4e30d0 0x4e3ac6 0x5ec117 0x50a9da 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x509d48 0x50aa7d 0x50c5b9 0x508245 0x50a080 0x50aa7d 0x50c5b9 0x508245 0x58958c 0x5a067e 0x50d966 0x509d48
```

**Comment by chervonij** [comment]
@camjac251 
this is github. no errors should be.
even if it does, then training just won't start.

about OOM.
I can do nothing with this.
this is an internal tensorflow error.
I don’t know how to get OOM on Colab, but lower settings of your model.

**Comment by chervonij** [comment]
Solved.
