### ISSUE TITLE
GRADIENT PAPERSPACE

### ISSUE THREAD

**Issue by rlkiran** [chervonij/DFL-Colab#20]
HEY mr.chervonji, can you please make a version of ipynb that works in gradient.paperspace.com,
they are giving quadro p5000 gpus for free.
please consider making it.

**Comment by chervonij** [comment]
@rlkiran 
Hey. I tried Paperspace.
Unfortunately, there isn’t the same user-friendly interface as in Colab. For a simple user it will be too complicated. Therefore, I will not do IPython Notebook for Paperspace.

However, if you are familiar with Python programming, you can run DeepFaceLab yourself.
