### ISSUE TITLE
No merging!

### ISSUE THREAD

**Issue by christiandios** [chervonij/DFL-Colab#21]
Hi!, i tried this out and after a few hours of working, could get this to run!. The thing is, when i get my result_video it doesn't have the faces merged. I checked all the folders with de pictures, and they are correct, somehow it didn't merge de data_dst and data_src. I always left the default prompted options and used SAEHD as recomended, any idea of where might be the error? Thanks.

**Comment by chervonij** [comment]
Do you know what the "issue" section is for? 
This is not a bug, merge is working fine. 
Look for a problem in your facesets.

**Comment by christiandios** [comment]
Sorry didn't mean to offend you, just was asking for suggestions.
