### ISSUE TITLE
Colab disconnected in just 40 minutes

### ISSUE THREAD

**Issue by reimond16** [chervonij/DFL-Colab#23]
Hello, as I understand it, Colab must let me work for 12 hours, so DFL_Colab makes a backup every 11 hours.
Well, only the first day I used Colab allowed me to work 12 hours. Now it goes offline due to Colab usage limits in under 45 minutes.

The main problem is that when Colab disconnects, the workspace folder disappears and I cannot find a way to make a copy to drive of what has already been worked.

Somebody help me please?
Sorry for my English but I am Spanish.

**Comment by khanhtrancse** [comment]
Me too

**Comment by chervonij** [comment]
@reimond16 @khanhtrancse 
Hey. I can not help with these disconnects. The problem is on Google’s side. 
I know for sure that buying Pro version solves this, but it's up to you (to buy or not).

I can also make it possible to configure the time for backup. 
There is already an option for backup every hour.

**Comment by reimond16** [comment]
Thanks for your answer. My question now is: How does that backup already configured work ?. If the answer is that it automatically backs up to Drive, in my case it doesn't happen. I always stop Training and make the copy manually using the "Export to Drive" option.

Thank you.

**Comment by chervonij** [comment]
@reimond16 
yes, turn on "Backup every hour" and the backup is uploaded to Drive under the name "workspace.zip" every hour of training.

everything is working fine.

**Comment by reimond16** [comment]
Well, I'm doing something wrong. In my case it does not make the copy.
Don't worry, because Google Colab keeps running for a short time, I make copies manually.

Thank you for your work, chervonij.
