### ISSUE TITLE
workspace.zip 

### ISSUE THREAD

**Issue by mzmfarid** [chervonij/DFL-Colab#24]
Hey

I have faced some issues while creating workspace.
can you please share workspace.zip with me.

Thank You

**Comment by chervonij** [comment]
@mzmfarid 
Hi!
There is default test workspace with extracted faces:
https://mega.nz/file/hNpVgaLS#HLQJwcnOzisEG7HDgBxCcF-awl9j-XQXGwgTWSxHD10

Also, to understand workflow try desktop version of DeepFaceLab

**Comment by mzmfarid** [comment]
@chervonij  thank you. I will look into it

**Comment by nicolas-gervais** [comment]
> @mzmfarid
> Hi!
> There is default test workspace with extracted faces:
> https://mega.nz/file/hNpVgaLS#HLQJwcnOzisEG7HDgBxCcF-awl9j-XQXGwgTWSxHD10
> 
> Also, to understand workflow try desktop version of DeepFaceLab

Where do I put this? What do I do with this?
