### ISSUE TITLE
imgaug / albumentations error

### ISSUE THREAD

**Issue by overclockedllama** [chervonij/DFL-Colab#25]
Hi,

I try to run `Install or update DeepFaceLab from Github` script but get this error
```py
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
```

**Comment by chervonij** [comment]
@overclockedllama 
Hi. And? What's the problem?
This error says about nothing.

**Comment by overclockedllama** [comment]
I have not encountered an error yet, as I am still learning how to use the software. Just that it is a requirement so I thought it would be important for something

**Comment by chervonij** [comment]
@overclockedllama 
This is just a version mismatch. Nothing serious. Everything is working.

**Comment by overclockedllama** [comment]
Oh ok thanks
