### ISSUE TITLE
Error while mounting workspace.zip from gdrive

### ISSUE THREAD

**Issue by justinjohn0306** [chervonij/DFL-Colab#26]
I'm trying to mount from gdrive but it come back with error: 
Mounted at /content/drive
/content
cp: error reading '/content/drive/My Drive/workspace.zip': Input/output error
[workspace.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of workspace.zip or
        workspace.zip.zip, and cannot find workspace.zip.ZIP, period.
Done!

**Comment by chervonij** [comment]
@justinjohn0306 

it's google's issue with connecting to GDrive.

**Comment by Oinksauce** [comment]
I have this same issue.  Any workarounds?
