### ISSUE TITLE
ImportError: cannot import name 'keras_export - this has become a permanent thing

### ISSUE THREAD

**Issue by Orchoidizer** [chervonij/DFL-Colab#29]
Hi @chervonij 

OK, so there IS a workaround for this problem but how long are we going to have to use it.

I though it had been fixed but I still have to use the (very time consuming) workaround every time I start a new project.

Any news regarding this?

**Comment by chervonij** [comment]
@Orchoidizer DFL-Colab 2.0 works fine.
I don't care about DFL 1.0
Its outdated thing.
