### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by Greywolf22** [chervonij/DFL-Colab#3]
So I started the training last night and closed the browser. After 10 minutes or so, I open the browser again and saw that instance was still running then I closed the browser again. Next day I check the instance only to find out that instance is terminated and no models have been uploaded to the drive.

What is the correct usage here? Should I keep the browser open for 11 hours? Why model hasn't been uploaded to the drive?

**Comment by chervonij** [comment]
This is how Google Colab works. In order for your training to work for 11 hours, your browser should be open. If you close the browser window, the machine only works for 2-3 hours. Auto Backup during training is set for 11 hours.  Therefore, the model was not uploaded on the drive.

**Comment by Greywolf22** [comment]
Got it thx for the reply. I think it would be better to give Auto Backup options to user. For example, every 2 hours model would be uploaded to drive. So even after browser closes for some reason, model would not be lost. Is this hard to implement?

**Comment by chervonij** [comment]
We are very lucky that there is auto backup in general. Only thanks to iperov did we have this opportunity, because it required a change in the DFL code itself. Currently, auto backup is stable. Just do not close your browser.

**Comment by Greywolf22** [comment]
got it. thx
