### ISSUE TITLE
Error When Importing from Google Drive

### ISSUE THREAD

**Issue by jaywhack21** [chervonij/DFL-Colab#30]
Hi,

I'm receiving the error below when I attempt to import a Workspace.zip from my Google Drive.

Can this please be reviewed and corrected?

<img width="495" alt="Screen Shot 2020-08-14 at 9 52 41 AM" src="https://user-images.githubusercontent.com/65094841/90262932-90e72100-de14-11ea-8900-0b645e99dc23.png">

Thanks!

**Comment by chervonij** [comment]
fixed
