### ISSUE TITLE
Colab Disconnects

### ISSUE THREAD

**Issue by PvtSec** [chervonij/DFL-Colab#31]
# Faceset Enhancer creates Trouble
On executing this cell, after a few minutes, Colab automatically disconnects and shows Connect without GPU. I think its like some GPU limit exceeded. 
Any tuning required to execute this cell without any disconnection?

**Comment by chervonij** [comment]
@PvtSec 
It doesn't depend on any particular cell. 
It all depends on the availability of GPUs. 
There is nothing to discuss here.

Issue closed.
