### ISSUE TITLE
Error: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by tania010** [chervonij/DFL-Colab#34]
Have started getting error:

[CPU] : CPU
  [0] : Tesla V100-SXM2-16GB

[0] Which GPU indexes to choose? : 
0

Error: module 'tensorflow' has no attribute 'ConfigProto'
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 55, in trainerThread
    debug=debug,
  File "/content/DeepFaceLab/models/ModelBase.py", line 151, in __init__
    nn.initialize(self.device_config)
  File "/content/DeepFaceLab/core/leras/nn.py", line 101, in initialize
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

when using %cd ./DeepFaceLab
!git checkout d1a5639e9083508207962f9bd1392af145ad7c88

using that commit used to work fine a few months ago.

**Comment by chervonij** [comment]
use latest version

**Comment by tania010** [comment]
> use latest version

models trained using the latest colab version do not work on the last fanseg PC version. that's why i'd been using the mentioned commit.

**Comment by tania010** [comment]
opening the commit gives the error: This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

don't know if removing the commit from the repository is causing the error or not.
_**All i need is a commit which works with the last fanseg PC version.**_

Using any other commit uses: "Uniform yaw distribution of samples" as one of the training options which the fanseg PC version does not, thus creating incompatibility between the 2.

**Comment by chervonij** [comment]
@tania010 
_"This commit does not belong to any branch on this repository"_
This is because this commit does not belong to **THIS** repository. It refers to the DeepFaceLab repository. Do you know how github works?

I don't support old versions.
Fanseg has been removed and replaced by XSeg.
It's not my problem that you don't want to use the latest version.

**Comment by chervonij** [comment]
You set some commits yourself. 
Why should I care that something is not working for you?

If you are modifying a workflow, then you need to understand what you are doing. 
I'm not going to solve every problem that comes due to the modifications.
