### ISSUE TITLE
value error no training data provided

### ISSUE THREAD

**Issue by nicolas-gervais** [chervonij/DFL-Colab#35]

**Comment by nicolas-gervais** [comment]
![image](https://user-images.githubusercontent.com/46652050/104818730-5d5f5700-57f7-11eb-9af6-d25f538eba04.png)

**Comment by nicolas-gervais** [comment]
![image](https://user-images.githubusercontent.com/46652050/104819982-9dc2d300-57ff-11eb-83f2-1e5dd511d70e.png)

**Comment by chervonij** [comment]
@nicolas-gervais 

Read guide.
https://mrdeepfakes.com/forums/thread-guide-deepfacelab-2-0-google-colab-guide

**Comment by nicolas-gervais** [comment]
I did, it's very unclear.

**Comment by Orchoidizer** [comment]
You can see here that there is no data in the 'data_dst/aligned' folder.
There also may not be any data in the 'data_src/aligned' folder but cant be sure as you haven't 'expanded' the view for that folder.

> ![image](https://user-images.githubusercontent.com/46652050/104819982-9dc2d300-57ff-11eb-83f2-1e5dd511d70e.png)

**Comment by chervonij** [comment]
@nicolas-gervais 
Error "No training data provided" means that you don't provide data for training (obviosly).
If you newbie, than read about DeepFaceLab work process.
I write about it on main page.

> **DFL-Colab uses DeepFaceLab and to understand the workflow, you should first understand the DeepFaceLab workflow.**
