### ISSUE TITLE
it says ''/content python3: can't open file 'DeepFaceLab/main.py': [Errno 2] No such file or directory'' while extracting frames in google colab

### ISSUE THREAD

**Issue by amal165** [chervonij/DFL-Colab#38]

**Comment by chervonij** [comment]
fixed

**Comment by d3ss3rt** [comment]
I'm getting the same thing
![image](https://user-images.githubusercontent.com/93103186/140578693-e594edb5-aac2-4abe-98af-51ce83a75fd3.png)

**Comment by chervonij** [comment]
@d3ss3rt 
All works fine. 
It looks like you didn't install DFL.

**Comment by 23031973** [comment]
I have the same problem .... I also install the DFL  on here and i also have it on my computer ready for work 
Training


Model:

SAEHD
Backup_every_hour:

Silent_Start:

/content
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Creating workspace archive ...
Archive created!
Time to end session: 12 hours
python3: can't open file 'DeepFaceLab/main.py': [Errno 2] No such file or directory

**Comment by 23031973** [comment]
And i also remember that , when i tried to unzip the DEEP FAKE LAB  it was a message what it is say something is missing ..... In my computer it works fine , but the missing file may be exactly the one it is need on google colab
