### ISSUE TITLE
File Browser randomly disappearing

### ISSUE THREAD

**Issue by Orchoidizer** [chervonij/DFL-Colab#42]
This issue with the file browser randomly disappearing is really getting so annoying now.

Has anybody discovered any ways to stop this happening or at least a workaround for when it does.

The only way to bring it back is to terminate whichever process your working in and restart it which is an absolute pain if it disappears when your in the middle of merging especially!

![Capture2](https://user-images.githubusercontent.com/54647922/123174884-c28b3880-d478-11eb-87c2-4a0de806e24b.JPG)

**Comment by chervonij** [comment]
@Orchoidizer 
Why are you writing this to me? 
This issue is not relevant to my project. 
It would be much more logical to write to the Google Colab repository, rather than create a useless issue here.

**Comment by Orchoidizer** [comment]
@chervonij 

Ah, OK . I had no idea that it was not relevant to the project.
Please accept my sincerest apologies.
