### ISSUE TITLE
Why don't put the workspace on Google Drive?

### ISSUE THREAD

**Issue by LZY2006** [chervonij/DFL-Colab#43]
In this way, we don't need to save workspace to Google Drive manually. Isn't it better?

**Comment by chervonij** [comment]
@LZY2006 
1. It is not data safe. If there is a slight lag with Colab-Drive connection, then model will not be saved correctly.

2. Drive has only 15 GB for free use. And Colab is about 30 GB. Drive has enough space to store necessary workspace data (facesets, model, original dst video), but this may not be enough if you are extracting frames. Extra 15 GB in Colab can play a big role here.

3. This is my vision of workflow. Drive for storing data, Colab for working with data.

**Comment by LZY2006** [comment]
Well, if you use Colab very often, then the usage limit will be very low, so you will lose your data if you don't save it in time.

**Comment by chervonij** [comment]
@LZY2006 
So, if you use Colab a lot, why don't you buy a Colab Pro subscription? This solves all your problems. 10$ for such hardware is quite cheap.

**Comment by LZY2006** [comment]
Because that service isn't available in my country.

**Comment by chervonij** [comment]
@LZY2006 
What prevents you from registering a new account and specifying a country that supports it?

**Comment by Cioscos** [comment]
> Because that service isn't available in my country.

Me from Italy, I use Colab Pro without any blocks. Google wants just your money ;)

**Comment by LZY2006** [comment]
I'm in China, and a lot of people buy this service, the price is so low that Google can't make money from it, so Google banned Chinese bank cards. @chervonij

**Comment by LZY2006** [comment]
Google has withdrawn from Mainland China in 2010, so Google can make little money from Chinese people. @Cioscos

**Comment by chervonij** [comment]
@LZY2006 
I can't get a point. Price is the same as in any other country. 
Why cards of Chinese banks banned, but other not?

Even so, what do you suggest? Completely change workflow just for you?

**Comment by chervonij** [comment]
Instead of this conversation, you could have changed the installation and launch paths of DFL in my notebook long ago. And use it the way you like.

**Comment by LZY2006** [comment]
OK, I've edited it manually, thanks.
