### ISSUE TITLE
Google Colab Auto Deletes "DeepFaceLab" Folder

### ISSUE THREAD

**Issue by qkum** [chervonij/DFL-Colab#49]
**Merry Christmas, lovely fellow nerds.**

Is it just me, or is Google Colab on purpose messing with us?

I'm paid Premium++ and it seems they even mess with their paying customers....

It happened a few times in a row today...That the "DeepFaceLab" folder got deleted instantly after installation and my script errors out "No folder named 'content/DeepFaceLab'" etc.

And yesterday a few times it "stopped" during the Extraction of frames from a video. With no explanation whatsoever.
The random stops during Frame Extraction were not a RAM or Harddisk space problem. The full video is cut into 10-minute parts.
I don't even use any GPU for extracting frames so I don't understand why they seem to sabotage my work. 

**Let's assume they delete "DeepFaceLab" on purpose, for a moment:**
They don't know if I'm using DeepFaceLab for company productions or hobby projects. How could they defend deleting "DeepFaceLab" the second after I installed it?

- What is your experience friends and what are your thoughts? 🤔 

@chervonij

**Comment by qkum** [comment]
I have not even been using Google Colab much yet. I bought premium++ like 3 days ago when everything was just working for "free".

It is not like I have been abusing their service for months for free, or over-using the paid version 24/7, with GPU and it all.

Not at all. Just playing with DeepFaceLab and a video and around day 3-4 using the Colab Notebook version of DeepFaceLab + Premium++ membership - this happens.

**Comment by qkum** [comment]
This is exactly why our world should not be run by algos.

1) They will make random mistakes.
2) No one got the blame for those mistakes (the company may say they take full responsibility, but that is a lie in reality)
3) Companies/Bad people can do "bad things" and then claim it was the algos that made a mistake and not management....

**Comment by chervonij** [comment]
Hi. Merry Christmas to you too. 
I haven't noticed Colab intentionally deleting the DeepFaceLab folder. 
I have been using Colab constantly for the last two months.

However, I can't be 100% sure about Google's actions and their policy on Colab. 
Since, "shadow" bans are not spelled out anywhere in the rules either, but its definitely exist.

All I can say is that in terms of my code, everything works fine.

**Comment by chervonij** [comment]
For example, I use 3 accounts in rotation to avoid a shadow ban. 
It takes no more than a month for one account, then I change to the next. 
And so on in a circle. 

Thus, each account is one month of work and two months of "rest".

**Comment by chervonij** [comment]
Сlosed due to inactivity.
