### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by somilhyperanna** [chervonij/DFL-Colab#5]
Running Latest Colab gives following exception while Training Model (Step 4).

Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 208, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/content/DeepFaceLab/models/ModelBase.py", line 398, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/content/DeepFaceLab/models/ModelBase.py", line 398, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 58, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.

I had it working before but not sure what has changed.

**Comment by chervonij** [comment]
There were no changes.
Just tested and everything works fine.
Check your workspace data.

**Comment by somilhyperanna** [comment]
Could be. Is there any sample workspace I can use. 

The workspace structure I used before had
Archive:  workspace_test.zip
   creating: workspace/
   creating: workspace/data_dst/
  inflating: workspace/data_dst.mp4  
   creating: workspace/data_dst/aligned/
   creating: workspace/data_src/
  inflating: workspace/data_src.mp4  
   creating: workspace/data_src/aligned/
   creating: workspace/model/

**Comment by somilhyperanna** [comment]
I found the issue in my workspace.  All good.

**Comment by chervonij** [comment]
good, issue closed.
