### ISSUE TITLE
Colab sessions getting ended automatically 

### ISSUE THREAD

**Issue by xdonaskelva** [chervonij/DFL-Colab#53]
it started happening since yesterday google colab is getting ended automatically after 15-20 mins i also tried with multiple accounts and the results are same.

**Comment by chervonij** [comment]
@xdonaskelva 
This may be due to the new Colab policy

![image](https://user-images.githubusercontent.com/42957568/172414747-3cab8b0a-efa2-42ef-a4c3-88bc9060abe7.png)

**Comment by chervonij** [comment]
I can't help with this.
