### ISSUE TITLE
During the `Install or update DeepFaceLab from Github` phase there was an error

### ISSUE THREAD

**Issue by haveaguess** [chervonij/DFL-Colab#56]
During the `Install or update DeepFaceLab from Github` phase there was an error

```
Cloning into 'DeepFaceLab'...
remote: Enumerating objects: 8045, done.
remote: Total 8045 (delta 0), reused 0 (delta 0), pack-reused 8045
Receiving objects: 100% (8045/8045), 828.69 MiB | 35.22 MiB/s, done.
Resolving deltas: 100% (5103/5103), done.
Updating files: 100% (211/211), done.
/content/DeepFaceLab
/content
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-2-ecc2ae5d3041>](https://localhost:8080/#) in <module>
     17   # fix linux warning
     18   # /usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
---> 19   fin = open("/usr/lib/python3.6/multiprocessing/semaphore_tracker.py", "rt")
     20   data = fin.read()
     21   data = data.replace('if cache:', 'if False:')

FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/multiprocessing/semaphore_tracker.py'
```

**Comment by haveaguess** [comment]
Seems like I could remove the semaphore tracker piece of code (tried updating from 3.6 to 3.8 which was available in colab but the file itself was still missing)

**Comment by reinhardmozes** [comment]
Same problem here. At one time, when this error occurred, I switch the "install" into "update" and re-run it. Somehow, it fixed the issue. But still, someone need to fix it

**Comment by rebrab001** [comment]
> Same problem here. At one time, when this error occurred, I switch the "install" into "update" and re-run it. Somehow, it fixed the issue. But still, someone need to fix it

Now "update" doesn't work anymore either.

**Comment by chervonij** [comment]
Try it now.

**Comment by rebrab001** [comment]
> Try it now.

Thank you, Its nice to be workng on videos again. 
I appreciate your efforts.

**Comment by chervonij** [comment]
@rebrab001 
It's not me. @ismatullayevs fixed it.

**Comment by rebrab001** [comment]
Thank you @ismatullayevs

**Comment by chervonij** [comment]
So, since it works now, issue closed.
