### ISSUE TITLE
Maybe use colabctl

### ISSUE THREAD

**Issue by TensorTom** [chervonij/DFL-Colab#6]
I recently started this repository: https://github.com/TensorTom/colabctl

I read your notebook and saw you are needing to use multiple colab notebooks. I thought you might want to check out my repo. Could use help improving if anyone has time and interest.

**Comment by chervonij** [comment]
I am very sorry that I answer, after so much time. 
The last few months have not worked on the repository.

I looked at your project, but I do not think we should use it for the DFL-Colab. 
Now the main problem is that Google blocks the backend when using Colab for a long time from the same account. So, for now, I close this issue.
