### ISSUE TITLE
Back-up model?

### ISSUE THREAD

**Issue by finargot** [chervonij/DFL-Colab#8]
Its possible to make auto-backup after 11 hours and Every hour backup only model - not whole workspace - as model usually is not more than 1 Gb, when Workspace could be 10 gb+

**Comment by chervonij** [comment]
In "Every hour backup" created archive with whole workspace and every hour it's update only model files in archive and upload to Drive. Connection speed Colab-Drive is very high, so I don't see problem here.

**Comment by finargot** [comment]
Oh great, thanks. Regarding 

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Is it ok?

**Comment by chervonij** [comment]
@finargot 
Yes. This is just warning, not error. It's fine.
