### ISSUE TITLE
Anyone want to run through how to use this?

### ISSUE THREAD

**Issue by yujinha0** [chervonij/DFL-Colab#9]
Can someone give me a definitive run through on how to use this in Google Colab. how to set up your workspace etc. The comments in the other issues tab is mainly in Russian. Cheers.

**Comment by chervonij** [comment]
@yujinha0 
Hi!  Here is full tutorial: https://mrdeepfakes.com/forums/thread-deepfacelab-google-colab-tutorial

**Comment by yujinha0** [comment]
Thanks my guy!
